export const LOGIN = 'LOGIN';
export const CREDENTIAL = 'CREDENTIAL';
export const VERIFY = 'VERIFY';
export const LOGOUT = 'LOGOUT';
export const SUBSCRIBE = 'SUBSCRIBE';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export const UPDATE_CURRENT_SEARCH = 'UPDATE_CURRENT_SEARCH';
export const CLEAR_CURRENT_SEARCH = 'CLEAR_CURRENT_SEARCH';
export const UPDATE_RECENT_SEARCHES = 'UPDATE_RECENT_SEARCHES';

export const RETRIEVE_CART = 'RETRIEVE_CART';
export const INC_ITEM = 'INC_ITEM';
export const DEC_ITEM = 'DEC_ITEM';
export const DISCOUNT = 'DISCOUNT';
export const TRACK_START = 'TRACK_START';
export const STATUS_UPDATE = 'STATUS_UPDATE';
export const TRACK_END = 'TRACK_END';
export const UPDATE_TRACK_COORDINATE = 'UPDATE_TRACK_COORDINATE';

export const RETRIEVE_ADDRESS = 'RETRIEVE_ADDRESS';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS'; 
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';